### ISSUE TITLE
feature file can't be downloaded, link doesn't work

### ISSUE THREAD

**Issue by DilinaHirantha** [MKLab-ITI/FIVR-200K#4]

**Comment by gkordo** [comment]
Hi, thanks for bringing it to my attention. Can you please elaborate a bit more? Which link are you trying and what is the error you are getting?

**Comment by DilinaHirantha** [comment]
Hi, thanks for your consideration, given link for global features https://ndd.iti.gr/features/  can't be reached, how ever I managed to download them using the evaluation file

**Comment by DilinaHirantha** [comment]
Also, downloading fivr-5k it bit critical cause need lot of storage, but if download few number of videos and still can we generate  the same evaluation results?

**Comment by gkordo** [comment]
> Hi, thanks for your consideration, given link for global features https://ndd.iti.gr/features/ can't be reached, how ever I managed to download them using the evaluation file

Great! Still, we have fixed the issue, so now the link should work.

> Also, downloading fivr-5k it bit critical cause need lot of storage, but if download few number of videos and still can we generate the same evaluation results?

Regarding this issue, you can download a subset of FIVR-5K and use the `evaluation.py` script just by providing the ids of the videos you downloaded to the `--dataset_ids` argument. Yet, the results would not be the same as the videos set used for evaluation is a critical factor that affects the output scores.

**Comment by zhang123-sys** [comment]
![image](https://user-images.githubusercontent.com/63956071/227861505-bd79ad48-1734-4332-9911-8d41d842b8df.png)

**Comment by gkordo** [comment]
@zhang123-sys I migrated the code to [yt-dlp](https://github.com/yt-dlp/yt-dlp), so the video downloading should work now.
